'''Java decompiler; same as call javap with no flags.'''
import sys

from pyjvm.utils.javap import javap

def describe_class_from(path):
    '''Decompile and nicely print a class.'''
    klass = javap(path)
    line = []
    line.extend(klass.accessor)
    line.append(klass.class_or_interface)
    line.append(klass.class_name)
    if not super_is_object(klass):
        line.append('extends')
        line.append(klass.super_class)
    if len(klass.interfaces):
        line.append('implements')
        line.append(', '.join(klass.interfaces))
    line.append('{')
    print(' '.join(line))

    for field in klass.fields:
        if field.name == 'serialVersionUID':
            continue
        line = ["   "]
        line.extend(field.flags)
        line.append(field.type)
        line.append(field.name)
        print(' '.join(line) + ';')

    for method in klass.methods:
        if is_static_constructor(method.name):
            print('    static {};')
            continue
        if is_generated_by_java(method.name):
            continue
        line = ["   "]
        line.extend(method.flags)
        line.append(method.returns)
        signature = method.name
        if is_constructor(method.name):
            signature = klass.class_name
        signature += '('
        signature += ', '.join(method.params)
        signature += ')'
        line.append(signature)
        print(' '.join(line) + ';')

    print('}')

def super_is_object(klass):
    '''Returns true if super is of java.lang.Object.'''
    return klass.super_class == 'java.lang.Object'

def is_static_constructor(method_name):
    '''Returns true if this is static constructor.'''
    return method_name == '<clinit>'

def is_constructor(method_name):
    '''Returns true if this is a constructor.'''
    return method_name == '<init>'

def is_generated_by_java(name):
    '''Some structures are generated by java compiler.'''
    return '$' in name

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Provide parameter with path to a Java8 class file.")
    else:
        describe_class_from(sys.argv[1])
